version: '3.1'

services:
    db:
        build: ./postgres/.
        restart: always
        environment:
            POSTGRES_PASSWORD: password

    app:
        build: .
        restart: always
        ports:
            - 5555:5555
