version: '3.2'

services:
    db:
        build: ../postgres/.
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
    app:
        build: .
        restart: always
        ports:
            - 8080:8080

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
