version: '3.2'

services:
    db:
        build: ../postgres/.
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: password
    app:
        build: .
        restart: always
        ports:
            - 5555:5555
        environment:
            NODE_ENV: docker
        volumes:
          - ./src:/usr/src/app/src

    adminer:
        image: adminer
        restart: always
        ports:
            - 8929:8080
